### ISSUE TITLE
cmdline output has a typo

### ISSUE THREAD

**Issue by ort163** [muhlba91/icloud#11]
Hi 
Great tool. I used the `cmdline`

```
Version: 2.1.0
API version: 2.1.0
```
Output has a typo below:  `https` and not `hhtps`:
`Principal-URL: hhtps://p01-caldav.icloud.com`

**Comment by muhlba91** [comment]
Hi!

Thank you for submitting this issue. I will correct this typo in the next days once I got some free time.

Best, Daniel :)
