### ISSUE TITLE
Why no nicely formatted Markdown READMEs?

### ISSUE THREAD

**Issue by marcelstoer** [muhlba91/icloud#16]
Is there a specific reason you don't use Markdown, or any other [supported markup format](https://github.com/github/markup#markups), for your READMEs? Otherwise I'd be happy to create a PR to that effect.

**Comment by muhlba91** [comment]
Hi,

it is just an older project and there wasn't much of a need to update so far. However, I need to update the documentation this week either way, meaning I will update the README accordingly and include your other proposed changes as well. :)
